package fr.univtours.polytech.indexing_engine_mapreduce.query.job;

import java.util.concurrent.Callable;

import javax.xml.soap.Text;

import org.apache.hadoop.fs.Path;
import org.apache.hadoop.mapred.FileInputFormat;
import org.apache.hadoop.mapred.FileOutputFormat;
import org.apache.hadoop.mapred.JobClient;
import org.apache.hadoop.mapred.JobConf;
import org.apache.hadoop.mapred.RunningJob;

public class QueryJob implements Callable<String> {
	private String inputPaths;

	public void setInputPaths(String inputPaths) {
		this.inputPaths = inputPaths;
	}

	public String getInputPaths() {
		return inputPaths;
	}

	private String outputPath;

	public void setOutputPath(String outputPath) {
		this.outputPath = outputPath;
	}

	public String getOutputPath() {
		return outputPath;
	}

	private RunningJob runningJob;

	public RunningJob getRunningJob() {
		return runningJob;
	}

	public String call() throws Exception {
		JobConf job = new JobConf();
		job.setJarByClass(getClass());

		/* Autogenerated initialization. */
		initJobConf(job);

		/* This is an example of how to set input and output. */
		FileInputFormat.setInputPaths(job, getInputPaths());
		if (getOutputPath() != null)
			FileOutputFormat.setOutputPath(job, new Path(getOutputPath()));

		
		JobClient client = new JobClient(job);
		this.runningJob = client.submitJob(job);
		return runningJob.getID().toString();
	}


	
	@SuppressWarnings("unchecked")
	public static void initJobConf(JobConf conf) {
	
		conf.setInputFormat(org.apache.hadoop.mapred.TextInputFormat.class);

		conf.setMapperClass(fr.univtours.polytech.indexing_engine_mapreduce.query.mapred.QueryMapper.class);

		conf.setMapOutputKeyClass(org.apache.hadoop.io.Text.class);
		conf.setMapOutputValueClass(org.apache.hadoop.io.Text.class);

		conf.setPartitionerClass(org.apache.hadoop.mapred.lib.HashPartitioner.class);

		conf.setOutputKeyComparatorClass(org.apache.hadoop.io.Text.Comparator.class);

		conf.setReducerClass(fr.univtours.polytech.indexing_engine_mapreduce.query.mapred.QueryReducer.class);

		conf.setNumReduceTasks(1);
		conf.setOutputKeyClass(Text.class);

		conf.setOutputFormat(org.apache.hadoop.mapred.TextOutputFormat.class);

	}

}
