package fr.univtours.polytech.indexing_engine_mapreduce.query.job;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.concurrent.Callable;

import javax.xml.soap.Text;

import org.apache.hadoop.fs.Path;
import org.apache.hadoop.mapred.FileInputFormat;
import org.apache.hadoop.mapred.FileOutputFormat;
import org.apache.hadoop.mapred.JobClient;
import org.apache.hadoop.mapred.JobConf;
import org.apache.hadoop.mapred.RunningJob;

public class QueryJob implements Callable<String> {
	public static HashSet<String> documents = new HashSet<String>();
	
	public static HashMap<String, Double> question;
	
	public QueryJob(HashMap<String, Double> question)	{
		QueryJob.question = question;
	}
	
	private String inputPaths;

	public void setInputPaths(String inputPaths) {
		this.inputPaths = inputPaths;
	}

	public String getInputPaths() {
		return inputPaths;
	}

	private String outputPath;

	public void setOutputPath(String outputPath) {
		this.outputPath = outputPath;
	}

	public String getOutputPath() {
		return outputPath;
	}

	private RunningJob runningJob;

	public RunningJob getRunningJob() {
		return runningJob;
	}

	public String call() throws Exception {
		JobConf job = new JobConf();
		job.setJarByClass(getClass());

		/* Autogenerated initialization. */
		initJobConf(job);

		/* This is an example of how to set input and output. */
		FileInputFormat.setInputPaths(job, getInputPaths());
		if (getOutputPath() != null)
			FileOutputFormat.setOutputPath(job, new Path(getOutputPath()));

		/* You can now do any other job customization. */
		// job.setXxx(...);

		/*
		 * And finally, we submit the job. If you run the job from within
		 * Karmasphere Studio, this returned RunningJob or JobID is given to the
		 * monitoring UI.
		 */
		JobClient client = new JobClient(job);
		this.runningJob = client.submitJob(job);
		return runningJob.getID().toString();
	}


	/**
	 * This method is called from within the constructor to initialize the job.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Job Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initJobConf
	public static void initJobConf(JobConf conf) {
		// Generating code using Karmasphere Protocol for Hadoop 0.18
		// CG_GLOBAL

		// CG_INPUT_HIDDEN
		conf.setInputFormat(org.apache.hadoop.mapred.TextInputFormat.class);

		// CG_MAPPER_HIDDEN
		conf.setMapperClass(fr.univtours.polytech.indexing_engine_mapreduce.query.mapred.QueryMapper.class);

		// CG_MAPPER
		conf.setMapOutputKeyClass(org.apache.hadoop.io.Text.class);
		conf.setMapOutputValueClass(org.apache.hadoop.io.Text.class);

		// CG_PARTITIONER_HIDDEN
		conf.setPartitionerClass(org.apache.hadoop.mapred.lib.HashPartitioner.class);

		// CG_PARTITIONER

		// CG_COMPARATOR_HIDDEN
		conf.setOutputKeyComparatorClass(org.apache.hadoop.io.Text.Comparator.class);

		// CG_COMPARATOR

		// CG_COMBINER_HIDDEN

		// CG_REDUCER_HIDDEN
		conf.setReducerClass(fr.univtours.polytech.indexing_engine_mapreduce.query.mapred.QueryReducer.class);

		// CG_REDUCER
		conf.setNumReduceTasks(1);
		conf.setOutputKeyClass(Text.class);

		// CG_OUTPUT_HIDDEN
		conf.setOutputFormat(org.apache.hadoop.mapred.TextOutputFormat.class);

		// CG_OUTPUT

		// Others
	}

}
